/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Telas;

import Classes.Funcionario;
import Classes.TextFieldValidator;
import javax.swing.JOptionPane;

/**
 *
 * @author Ditto66
 */
public class Cadastro_Professores extends javax.swing.JFrame {

    TextFieldValidator validator = new TextFieldValidator();
    
    /**
     * Creates new form Cadastro_Professores
     */
    public Cadastro_Professores() {
        initComponents();
    }
    public Cadastro_Professores(String nome) {
        initComponents();
        jLabel1.setText(nome);
        
        jLabelMsg.setVisible(false);
        jLRGMsg.setVisible(false);
        jLCPFMsg.setVisible(false);
        jLEmailMsg.setVisible(false);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelMsg = new javax.swing.JLabel();
        jLRGMsg = new javax.swing.JLabel();
        jLCPFMsg = new javax.swing.JLabel();
        jLEmailMsg = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jLLimparBtn = new javax.swing.JLabel();
        jLCadastrarBtn = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(600, 516));
        setPreferredSize(new java.awt.Dimension(600, 544));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelMsg.setBackground(new java.awt.Color(231, 76, 60));
        jLabelMsg.setFont(new java.awt.Font("Open Sans", 1, 12)); // NOI18N
        jLabelMsg.setForeground(new java.awt.Color(255, 255, 255));
        jLabelMsg.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelMsg.setText("Por favor preencha todos os campos!");
        jLabelMsg.setOpaque(true);
        getContentPane().add(jLabelMsg, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 435, 230, -1));

        jLRGMsg.setBackground(new java.awt.Color(241, 196, 15));
        jLRGMsg.setFont(new java.awt.Font("Open Sans", 1, 12)); // NOI18N
        jLRGMsg.setForeground(new java.awt.Color(255, 255, 255));
        jLRGMsg.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLRGMsg.setText("Somente números!");
        jLRGMsg.setOpaque(true);
        getContentPane().add(jLRGMsg, new org.netbeans.lib.awtextra.AbsoluteConstraints(128, 185, 120, -1));

        jLCPFMsg.setBackground(new java.awt.Color(241, 196, 15));
        jLCPFMsg.setFont(new java.awt.Font("Open Sans", 1, 12)); // NOI18N
        jLCPFMsg.setForeground(new java.awt.Color(255, 255, 255));
        jLCPFMsg.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLCPFMsg.setText("Somente números!");
        jLCPFMsg.setOpaque(true);
        getContentPane().add(jLCPFMsg, new org.netbeans.lib.awtextra.AbsoluteConstraints(455, 124, 120, -1));

        jLEmailMsg.setBackground(new java.awt.Color(231, 76, 60));
        jLEmailMsg.setFont(new java.awt.Font("Open Sans", 1, 12)); // NOI18N
        jLEmailMsg.setForeground(new java.awt.Color(255, 255, 255));
        jLEmailMsg.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLEmailMsg.setText("Por favor insira um email válido!");
        jLEmailMsg.setOpaque(true);
        getContentPane().add(jLEmailMsg, new org.netbeans.lib.awtextra.AbsoluteConstraints(375, 185, 200, -1));

        jTextField1.setFont(new java.awt.Font("Open Sans", 0, 12)); // NOI18N
        jTextField1.setBorder(null);
        jTextField1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField1FocusLost(evt);
            }
        });
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField1KeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField1KeyTyped(evt);
            }
        });
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(358, 153, 210, -1));

        jTextField2.setFont(new java.awt.Font("Open Sans", 0, 12)); // NOI18N
        jTextField2.setBorder(null);
        jTextField2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField2KeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField2KeyTyped(evt);
            }
        });
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 153, 290, -1));

        jTextField3.setFont(new java.awt.Font("Open Sans", 0, 12)); // NOI18N
        jTextField3.setBorder(null);
        jTextField3.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField3FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField3FocusLost(evt);
            }
        });
        jTextField3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField3KeyTyped(evt);
            }
        });
        getContentPane().add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 214, 210, -1));

        jTextField4.setFont(new java.awt.Font("Open Sans", 0, 12)); // NOI18N
        jTextField4.setBorder(null);
        jTextField4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField4KeyTyped(evt);
            }
        });
        getContentPane().add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(276, 214, 290, -1));

        jTextField5.setFont(new java.awt.Font("Open Sans", 0, 12)); // NOI18N
        jTextField5.setBorder(null);
        jTextField5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField5KeyTyped(evt);
            }
        });
        getContentPane().add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 275, 540, -1));

        jTextField7.setFont(new java.awt.Font("Open Sans", 0, 12)); // NOI18N
        jTextField7.setBorder(null);
        jTextField7.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField7KeyTyped(evt);
            }
        });
        getContentPane().add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(358, 397, 210, -1));

        jTextField6.setFont(new java.awt.Font("Open Sans", 0, 12)); // NOI18N
        jTextField6.setBorder(null);
        jTextField6.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField6KeyTyped(evt);
            }
        });
        getContentPane().add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 397, 290, -1));

        jLLimparBtn.setPreferredSize(new java.awt.Dimension(34, 12));
        jLLimparBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLLimparBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLLimparBtnMouseEntered(evt);
            }
        });
        getContentPane().add(jLLimparBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 470, 300, 50));

        jLCadastrarBtn.setPreferredSize(new java.awt.Dimension(34, 12));
        jLCadastrarBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLCadastrarBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLCadastrarBtnMouseEntered(evt);
            }
        });
        getContentPane().add(jLCadastrarBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 470, 300, 50));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/CadastrarProfessorWindow.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 340, -1, -1));
        jLabel1.getAccessibleContext().setAccessibleName("user_id");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jLCadastrarBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLCadastrarBtnMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jLCadastrarBtnMouseEntered

    private void jLCadastrarBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLCadastrarBtnMouseClicked
        
        if(jTextField1.getText().equals("") || jTextField2.getText().equals("") || jTextField3.getText().equals("")
                || jTextField4.getText().equals("") || jTextField5.getText().equals("") || jTextField6.getText().equals("")
                || jTextField7.getText().equals("")){
            
            jLabelMsg.setVisible(true);
        }else if(!validator.emailValidate(jTextField4)){            
            jLEmailMsg.setVisible(true);      
        }else{
            
            jLEmailMsg.setVisible(false);  
            
            Funcionario fun = new Funcionario(jTextField2.getText(),jTextField6.getText(),jTextField7.getText());
            fun.setCPF(jTextField1.getText());
            fun.setRG(jTextField3.getText());
            fun.setEmail(jTextField4.getText());
            fun.setGraduacao(jTextField5.getText());
            fun.setTipo_user("3");
            String User_Login = jLabel1.getText();
            boolean cds = fun.cadastrar_funcionario( fun, User_Login);
            if(!(true == cds)){
                JOptionPane.showMessageDialog(null, "Cadastro Realizado com Sucesso");
                //jButton1ActionPerformed(evt);
            }
            else{
                JOptionPane.showMessageDialog(null, "Erro ao Cadastrar");  
            }
        }
    }//GEN-LAST:event_jLCadastrarBtnMouseClicked

    private void jLLimparBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLLimparBtnMouseClicked
        jTextField1.setText("");
        jTextField2.setText("");
        jTextField3.setText("");
        jTextField4.setText("");
        jTextField5.setText("");
        jTextField6.setText("");
        jTextField7.setText("");
    }//GEN-LAST:event_jLLimparBtnMouseClicked

    private void jLLimparBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLLimparBtnMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jLLimparBtnMouseEntered

    private void jTextField2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField2KeyTyped
        
    }//GEN-LAST:event_jTextField2KeyTyped

    private void jTextField2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField2KeyPressed
        validator.maxLengthLimit(jTextField2, 40);
    }//GEN-LAST:event_jTextField2KeyPressed

    private void jTextField1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyTyped
        validator.numericValidate(evt);
        validator.maxLengthLimit(jTextField1, 11);        
    }//GEN-LAST:event_jTextField1KeyTyped

    private void jTextField1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField1FocusGained
        jLCPFMsg.setVisible(true);
    }//GEN-LAST:event_jTextField1FocusGained

    private void jTextField1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField1FocusLost
        jLCPFMsg.setVisible(false);
    }//GEN-LAST:event_jTextField1FocusLost

    private void jTextField3FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField3FocusGained
        jLRGMsg.setVisible(true);
    }//GEN-LAST:event_jTextField3FocusGained

    private void jTextField3FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField3FocusLost
        jLRGMsg.setVisible(false);
    }//GEN-LAST:event_jTextField3FocusLost

    private void jTextField3KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField3KeyTyped
        validator.numericValidate(evt);
        validator.maxLengthLimit(jTextField3, 13);
    }//GEN-LAST:event_jTextField3KeyTyped

    private void jTextField4KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField4KeyTyped
        validator.maxLengthLimit(jTextField4, 30);
    }//GEN-LAST:event_jTextField4KeyTyped

    private void jTextField5KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField5KeyTyped
        validator.maxLengthLimit(jTextField5, 40);
    }//GEN-LAST:event_jTextField5KeyTyped

    private void jTextField7KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField7KeyTyped
        validator.maxLengthLimit(jTextField7, 20);
    }//GEN-LAST:event_jTextField7KeyTyped

    private void jTextField6KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField6KeyTyped
        validator.maxLengthLimit(jTextField6, 20);
    }//GEN-LAST:event_jTextField6KeyTyped

    private void jTextField1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyPressed
        
    }//GEN-LAST:event_jTextField1KeyPressed
            
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cadastro_Professores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cadastro_Professores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cadastro_Professores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cadastro_Professores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Cadastro_Professores().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLCPFMsg;
    private javax.swing.JLabel jLCadastrarBtn;
    private javax.swing.JLabel jLEmailMsg;
    private javax.swing.JLabel jLLimparBtn;
    private javax.swing.JLabel jLRGMsg;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelMsg;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    // End of variables declaration//GEN-END:variables
}
